name: Docker
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:21-alpine3.18
      env:
        API_URL: sample-url.com
      ports:
        - 80
    steps:
      - name: Log Node & OS Versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log Env
        run: echo $API_URL
      - name: Create a file
        run: echo 'Sample Text' > text.txt
      - name: Step Container
        uses: docker://node:21.4-alpine3.18
        with:
          entrypoint: /usr/local/bin/node
          args: -p 2+3
      - name: Step Container
        uses: docker://node:21.4-alpine3.18
        with:
          args: -v
      - name: Show file contents
        uses: docker://node:21.4-alpine3.18
        with:
          entrypoint: cat
          args: text.txt


